### ISSUE TITLE
Build PrRoIPooling on Windows 10

### ISSUE THREAD

**Issue by MMarvasti** [vacancy/PreciseRoIPooling#64]
Hi there,

Please let me know how I can build precise ROI pooling on windows 10, PyTorch 1.2.0, Python 3.7, and

What does the following mean:

For Windows Users
**!!! Have to copy cuda codes from src/* to tensorflow/prroi_pool/src/external/* **

Thnaks.

**Comment by vacancy** [comment]
See https://github.com/vacancy/PreciseRoIPooling/issues/58

**Comment by vacancy** [comment]
Also on the top of readme.

Causion: To install the library, please git clone the repository instead of downloading the zip file, since source files inside the folder ./pytorch/prroi_pool/src/ and tensorflow/prroi_pool/src/kernels/external are symbol-linked. Downloading the repository as a zip file will break these symbolic links. Also, there are reports indicating that Windows git versions also breaks the symbol links. See issues/58.
